using System;
using System.Collections.Generic;
using System.Text;

namespace Serverside.Enums {
    public enum VehicleModTypes {
        Spoilers,
        FrontBumper,
        RearBumper,
        SideSkirt,
        Exhaust,
        Frame,
        Grille,
        Hood,
        Fender,
        RightFender,
        Roof,
        Engine,
        Brakes,
        Transmission,
        Horns,
        Suspension,
        Armor,
        FrontWheel = 23,
        RearWheel,
        PlateHolder,
        VanityPlates,
        TrimDesign,
        Ornaments,
        Dashboard,
        DialDesign,
        DoorSpeakers,
        Seats,
        SteeringWheels,
        ColumnShifterLevers,
        Plaques,
        Speakers,
        Trunk,
        Hydraulics,
        EngineBlock,
        AirFilter,
        Struts,
        ArchCover,
        Aerials,
        Trim,
        Tank,
        Windows,
        Livery = 48
    }
}
